### ISSUE TITLE
Deploy to Euronext & Test servers

### ISSUE THREAD

**Issue by ro-savage** [Runn-Fast/deploy-to-heroku-action#10]
Looks like this code only deploys to runn-app-production
Could we make it deploy to runn-app-euronext as well?

Could we also add a case for "runn-app-test" where we can deploy to that by using the branch test?

https://github.com/Runn-Fast/deploy-to-heroku-action/blob/3a095dd68a8dff60270467336de1585f6b2cec9e/src/targets.ts#L30-L40

**Comment by stayradiated** [comment]
Ah, I forgot about Euronext -- that was one of the key reasons around rewriting it in Typescript as well!

In theory, I should just be able to add the Euronext config to this array and anything pushed to the `production` branch will be pushed to both production and Euronext servers.
