### ISSUE TITLE
Change to default to not deleting

### ISSUE THREAD

**Issue by ro-savage** [Runn-Fast/deploy-to-heroku-action#8]
Could we update the safety check to instead of checking if production/staging/etc.

We instead only delete if it has a "pr-" in the name?
Or if want to be extra safe something like `'runn-pr-\d+-app' | 'runn-pr-\d+-actions' | 'runn-pr-\d+-hasura'`

https://github.com/Runn-Fast/deploy-to-heroku-action/blob/3a095dd68a8dff60270467336de1585f6b2cec9e/src/heroku.ts#L113-L117

**Comment by stayradiated** [comment]
Yep, that is a solid idea, best to be on the safe side.

**Comment by stayradiated** [comment]
I didn't write it this way initially, because there were apps on Heroku with the old style naming convention (`runn-review-####-hasura`) that I wanted to clean up.
